### ISSUE TITLE
[Question] How to use / am I missing something?

### ISSUE THREAD

**Issue by tampiss** [Samsung/SamsungAutomationStudio#15]
Hi, I have Raspi 4 with Node-RED installed. I have installed this plugin to enable me to connect to Smartthings cloud and obtain status of my Samsung Washer and Samsung Dryer. When I create a new flow, add My device node -  fill in the token, I get the list of my devices. I unselect all and chose only 1 (for example Samsung Washer), then I deploy. After that, I add status or event node and sometimes I can choose the appropriate selects, but most of the time they are empty...

Any hints please?
Thank you, Martin

**Comment by shgood** [comment]
Hi, 

Could you let us know a more detailed situation?
i.g. when your device disappears / whether node-red  was restarted or not

And It would be better if you could give us browser and node-red runtime logs.

Thank you!

**Comment by tampiss** [comment]
@shgood well I actually saw the list of devices in Status or Event nodes once and I am unable to simulate it again. Since now, I always get an empty select boxes. I tried to uninstall the plugin, but that did not help. Please see attached files, to clarify my problem. For example, if I open the Command node, the list of devices exists. By the way, what is the best way for you to get you the node-red runtime log? How to access it please? 

I am running node-red on Raspi 4, Homebridge image:
Node version is v14.16.1
NPM version 6.14.12
Node-RED 1.3.1
Your plugin 1.1.3

Browser/PC:
MacOS Big Sure 11.2.3
Safari 14.0.3 (tried dirrefent user agents for Chrome, Edge...)
Even tried Chrome app version 85.0.4183.83

![Snímek obrazovky 2021-04-21 v 9 05 47](https://user-images.githubusercontent.com/433677/115511477-29c21c00-a281-11eb-89cd-05cf42bcef0b.png)

![Snímek obrazovky 2021-04-21 v 9 07 02](https://user-images.githubusercontent.com/433677/115511500-30509380-a281-11eb-9570-424a20f39243.png)

![Snímek obrazovky 2021-04-21 v 9 07 28](https://user-images.githubusercontent.com/433677/115511520-35adde00-a281-11eb-8024-6325a82fe2ed.png)

![Snímek obrazovky 2021-04-21 v 9 07 55](https://user-images.githubusercontent.com/433677/115511544-3ba3bf00-a281-11eb-8706-e6d200bb3aa6.png)

**Comment by shgood** [comment]
1. event-device node work with "automation" node only. So in your case, event-device node doesn't work.

2. when you enter "F12" key on the chrome, you can see the chrome console log like below.
![이미지 033](https://user-images.githubusercontent.com/67676176/115662825-848b6e80-a37a-11eb-80de-01b0f712bba0.png)
If there are log messages, share them here.

3. could you share capabilities list of your devices? 
In the device list, you can get capabilities information like below.
![이미지 031](https://user-images.githubusercontent.com/67676176/115661736-e0ed8e80-a378-11eb-8f23-96f4c6f76bb5.png)
Because there may be no capability available for status-node if only command-device node works.

**Comment by tampiss** [comment]
@shgood Hi, bellow are the print-screens. Hope it helps. Martin

![Snímek obrazovky 2021-04-22 v 8 08 13](https://user-images.githubusercontent.com/433677/115664616-5be78280-a342-11eb-98d6-57796bcf62d4.png)
![Snímek obrazovky 2021-04-22 v 8 08 27](https://user-images.githubusercontent.com/433677/115664623-5db14600-a342-11eb-90d6-e166e2be8b9b.png)
![Snímek obrazovky 2021-04-22 v 8 07 34](https://user-images.githubusercontent.com/433677/115664627-5e49dc80-a342-11eb-843e-eb975312ad5b.png)

**Comment by shgood** [comment]
Hi, 
I think It's related to  node-red 1.3.1 release's issue
> https://github.com/node-red/node-red/issues/2933

please, install node-red 1.3.2 or 1.3.3.

**Comment by tampiss** [comment]
@shgood YES!! 🙌 👏 👍 this fixed the issue.. May I ask one more question? Does it mean, I have to have each device on separate flow? Its not problem for me, but just asking. If I create flow, select My device node and select 2 devices, when I use Event/Status node, I only get active the first one and the rest is disabled. Thank you, Martin

**Comment by shgood** [comment]
No, you don't need to.

If a device is disabled on the select, that device is not an appropriate device used by Event/Status/Command node.

It means that there are some conditions.
i.g. Status node use device that has attributes property  / Command node use device that has command property ...

And when you mouse over the disabled select option, you can see the reason why the device is disabled.

**Comment by tampiss** [comment]
@shgood see my trouble. If I create flow, select My Device, then select 2 devices, deploy. Then I add Event node and only first device is selected. If I open the device select, all devices are disabled (see print-screen)... So I can only work with the one preselected.. 

Now, I have 2 flows, where in both I select different Device in My device node.. By adding Event node to each flow, I have correctly preselected device and I can work with it.. yet still all devices are disabled when I open the select.

![Snímek obrazovky 2021-04-22 v 10 54 26](https://user-images.githubusercontent.com/433677/115686357-65c8b000-a359-11eb-97c4-e224f43a2862.png)
![Snímek obrazovky 2021-04-22 v 10 55 06](https://user-images.githubusercontent.com/433677/115686366-68c3a080-a359-11eb-9d6e-326e49a4e760.png)
![Snímek obrazovky 2021-04-22 v 10 55 02](https://user-images.githubusercontent.com/433677/115686369-68c3a080-a359-11eb-952f-d7af7fe01545.png)

**Comment by shgood** [comment]
The current behavior seems to be a bug in a safari browser. 
In a normal case,  a disabled device cannot be selected.

But. as I said, event-device node work with "automation" node only.
In event-node, you can select the only device set in "device profile" node. 
Because They are set in my-device node, those devices are disabled.

**Please, use status-node** instead of event-node to get device status.

**Comment by kudlaaaty** [comment]
Hi,
I have very simmilar problem. I'm using Samsung Automation Studio Palette (1.1.6) in Node Red (1.3.5) in Home Assistant (2021.6.5). When I initailly insert "My device" node, and put there a token devices are visible:
![image](https://user-images.githubusercontent.com/86081558/122588076-f0c6dd80-d05e-11eb-8343-06aa4f229add.png)

After that I can i.e. add command node and set some device property:

![image](https://user-images.githubusercontent.com/86081558/122588504-79457e00-d05f-11eb-975a-471242876f0e.png)

Afer deploy everything is working just fine, but when i left the Node Red and open it again, devices and other node properties of "My device" node are gone:

![image](https://user-images.githubusercontent.com/86081558/122588843-dc371500-d05f-11eb-8564-557c0ff1e092.png)

as well as in the "Command" node:

![image](https://user-images.githubusercontent.com/86081558/122588925-f2dd6c00-d05f-11eb-9068-5df881168e93.png)

I've found this behaviour very similar to the case described in this topic, however I'm using version of Node Red above the 1.3.3. I've tried also different browsers (Chrome, Edge, FireFox) but witout any success. Any ideas what could gone wrong?

**Comment by RitaSghe** [comment]
I have the same problem ...

![Screenshot_2021](https://user-images.githubusercontent.com/81916825/123904263-7b1d1480-d970-11eb-8178-4bede609bf38.png)

**Comment by kudlaaaty** [comment]
@shgood after upgrade to 1.1.7 this behaviour still exists

**Comment by shgood** [comment]
Hi, @kudlaaaty , @RitaSghe.
Thank you for your comment.

1.1.9 version has been released today to fix SmartThings my-device bug.

Please, update and use the new version.
Thank you.

**Comment by kudlaaaty** [comment]
@shgood 
Hi, I've just updated to 1.1.9 but this behaviour still exist.

**Comment by shgood** [comment]
@kudlaaaty 

> Afer deploy everything is working just fine, but when i left the Node Red and open it again, devices and other node properties of "My device" node are gone:
> 
> ![image](https://user-images.githubusercontent.com/86081558/122588843-dc371500-d05f-11eb-8564-557c0ff1e092.png)
> 
> as well as in the "Command" node:
> 
> ![image](https://user-images.githubusercontent.com/86081558/122588925-f2dd6c00-d05f-11eb-9068-5df881168e93.png)
> 
> I've found this behaviour very similar to the case described in this topic, however I'm using version of Node Red above the 1.3.3. I've tried also different browsers (Chrome, Edge, FireFox) but witout any success. Any ideas what could gone wrong?


After re-open node-red, Your my-device node's properties all disappear ?? even a 'Personal Access Token'? 

If there are console error messages, could you let me know that or your server error messages? 
(press 'F12' to open chrome DevTools, you can find log message in the 'console' tab)

**Comment by kudlaaaty** [comment]
In "My device" node, PAT exists, but devices are gone:
![image](https://user-images.githubusercontent.com/86081558/124242704-531ee400-db1d-11eb-9903-b6b32bd6c714.png)

There are some errors and wrnings: 
![image](https://user-images.githubusercontent.com/86081558/124243596-58306300-db1e-11eb-972d-37c7168893c3.png)

**Comment by RitaSghe** [comment]
After 9 days not news?

**Comment by shgood** [comment]
Hi,
sorry for the late reply.

404 error is occurring, I think that it is related to node-red's 'httpNodeApp' root setting.
so, I fix the SmartThings node to using 'httpNodeApp' root setting.

Please update version '1.1.10' and check.
Thank you

**Comment by RitaSghe** [comment]
After update to 1.1.10 the bug is fixed ......

**Comment by kudlaaaty** [comment]
@shgood 
unfortunately after upgrade this bug still exist in my case...
![image](https://user-images.githubusercontent.com/86081558/125304032-89ced880-e32d-11eb-9aad-90f77b76d407.png)

I've tried in different browsers but without success.

**Comment by RitaSghe** [comment]
Sorry, I restart Raspberry and now I have the bug again ........

**Comment by kudlaaaty** [comment]
Any chances to get this bug rid off? Currently, because of this bug almost whole palette is unusable

**Comment by kudlaaaty** [comment]
@shgood after upgrade to 1.1.11 error sitill exists:
![image](https://user-images.githubusercontent.com/86081558/126459792-7cd2203a-3446-4202-b882-3a7a75ac1a77.png)
![image](https://user-images.githubusercontent.com/86081558/126459892-0dc5bd15-d2f2-4da5-ab63-94b5e546b268.png)

**Comment by shgood** [comment]
@RitaSghe 

Are you using node-red 'adminAuth' option in 'setting.js'? 
It seems like related to auth_token because occurring 401 error.

Regarding that, the 1.1.11 version was released.

Please update version '1.1.11' and check.
Thank you

**Comment by shgood** [comment]
@kudlaaaty

It seems that your node-red path and httpNodeRoot path are different.
I mean,
httpNodeRoot = '/endpoint' that is set node-red settings.js
node-red path = 
![image](https://user-images.githubusercontent.com/67676176/126461055-b6409508-7c05-4915-87dc-2de890c0f990.png)

I think that maybe your node-red is running on k8s.

so, modify the path to your node-red path in the '101-SmartThings.js' file code.
https://github.com/Samsung/SamsungAutomationStudio/blob/63906763ab0ccdf1feb2fba4626773d85918795e/101-SmartThings.js#L38-L39

**Comment by kudlaaaty** [comment]
I've tried both options, however without success. Indeed this node-red is running on k8s. 

I've found that the correct URL is:
https://xxxxxxxxx.duckdns.org/api/hassio_ingress/2WYIo6nZdNVGqcJBLblrmI1_B8pC9V2wVTyz8Jjj7ek/endpoint/_smartthings/mydevices

I've change the path as follows but still node wants to read directly from "endpoint/_smartthings/mydevices"
![image](https://user-images.githubusercontent.com/86081558/126477081-3147386e-9984-41b6-a704-a160fa6bf320.png)

**Comment by shgood** [comment]
@kudlaaaty 

Hmm..

https://github.com/Samsung/SamsungAutomationStudio/blob/63906763ab0ccdf1feb2fba4626773d85918795e/101-SmartThings.html#L763-L777

Please try to change code like below (rollback '101-SmartThings.html')

```js
//line 765
                const root = '{your node-red path}';
```

e.g. 
```js
const root = '/api/hassio_ingress/2WYIo6nZdNVGqcJBLblrmI1_B8pC9V2wVTyz8Jjj7ek/endpoint/'
// or const root = 'api/hassio_ingress/2WYIo6nZdNVGqcJBLblrmI1_B8pC9V2wVTyz8Jjj7ek/endpoint/'
```

**Comment by kudlaaaty** [comment]
make a change in const root to:

![image](https://user-images.githubusercontent.com/86081558/126483302-42d2e9e6-056e-4c8e-a324-92cdb3d1a3ff.png)

do the trick! Thanks! 
however are there any chances to make it more "automatic" in feature releases?

**Comment by RitaSghe** [comment]
I have update version '1.1.11' and nothing has changed ....
Now I I'll explain what I do ....

Double click on the List device node and I have this situation:

![img01](https://user-images.githubusercontent.com/81916825/126485546-6a6e5923-0e29-4798-807b-5731886fd1a7.png)

So single click on the red check and I have this situation:

![img02](https://user-images.githubusercontent.com/81916825/126485625-a992c88c-111e-4d26-840e-d02791739c63.png)

Single click on button Cancel and Double click on the List device node again and I have this situation, the real correct list of devices:

![img03](https://user-images.githubusercontent.com/81916825/126485786-e34f0808-6f51-4af9-b439-fb40b3beb64b.png)

Now I click done and after Deploy.

Now Double click on the List device node and I have this situation:

![img01](https://user-images.githubusercontent.com/81916825/126485994-08dabecc-aad8-4329-92f8-4e59f76c576b.png)

Nothing has changed ....

**Comment by shgood** [comment]
@kudlaaaty , @RitaSghe 

could you try this code?

https://github.com/Samsung/SamsungAutomationStudio/blob/63906763ab0ccdf1feb2fba4626773d85918795e/101-SmartThings.html#L763-L775

change 'callMyDeviceApi' function to below code

```js
        function callMyDeviceApi(path){
            return new Promise((resolve,reject)=>{
                let root = RED.settings.httpNodeRoot||'';
                root = root.trim().replace(/^\/*/,'');
                if(/[^\/]$/.test(root)){root+='/';}
                $.ajax({url:root+path,type:"GET",dataType:'json'}).then(resolve,reject);
            })
        }
```

If it works, I will modify the code.

**Comment by RitaSghe** [comment]
I wanted to try the change of the code, but I found out that ......
I have a test environment on pc with ubuntu and one raspberry (os raspberry) with my home automation.
Since a while I didn't use the test environment because I connect directly by pc with firefox to node red on raspberry to modify the code.
This morning to test your code I update test environment (all the palette) and before update the code I test the node samsung ...
Well, in the test environment the node work fine and I have my devices without problem,  but if with the same firefox, in a new page, I connect the node red on raspberry, I have the problem, no devices in list ....

Can this help you?

**Comment by shgood** [comment]
@RitaSghe 
hmm, 


Your raspberry can connect SmartThings API?
node-red can communicate SmartThings API to work SmartThings nodes.
(raspberry in your case)

It seems 

> @kudlaaaty , @RitaSghe
> 
> could you try this code?
> 
> https://github.com/Samsung/SamsungAutomationStudio/blob/63906763ab0ccdf1feb2fba4626773d85918795e/101-SmartThings.html#L763-L775
> 
> change 'callMyDeviceApi' function to below code
> 
> ```js
>         function callMyDeviceApi(path){
>             return new Promise((resolve,reject)=>{
>                 let root = RED.settings.httpNodeRoot||'';
>                 root = root.trim().replace(/^\/*/,'');
>                 if(/[^\/]$/.test(root)){root+='/';}
>                 $.ajax({url:root+path,type:"GET",dataType:'json'}).then(resolve,reject);
>             })
>         }
> ```
> 
> If it works, I will modify the code.

**Comment by kudlaaaty** [comment]
@shgood 
I've changed this function and it seems that it works!

**Comment by RitaSghe** [comment]
@kudlaaaty 

Try to restart ... :)

**Comment by kudlaaaty** [comment]
@RitaSghe 
I've already done restart twice and still working

**Comment by shgood** [comment]
@RitaSghe 

'restart' means 'node-red server restart' or 'browser close and open'?
could you check '_smartthings/mydevices' response code in the 'network' tab? (e.g. 401 or 404)

And your raspberry can connect SmartThings API?
the node-red server can connect SmartThings to work SmartThings nodes.

**Comment by shgood** [comment]
@kudlaaaty 
Thanks a lot. 
I will modify the code like above in the new release.

**Comment by RitaSghe** [comment]
I mean restart node-red server ...
Error is 401

**Comment by kudlaaaty** [comment]
Yes, I've restarted whole node-red. 

AFAIK Rapsberry itself does not interact with ST API

**Comment by RitaSghe** [comment]
This is my situation after update, Nothing has changed ....

![img01](https://user-images.githubusercontent.com/81916825/128327290-ee1862af-8c72-4e9a-b42e-a2c63803403e.png)

![img02](https://user-images.githubusercontent.com/81916825/128327322-1f9546ca-ac81-44f2-8249-34d3f921aec9.png)

**Comment by RitaSghe** [comment]
You can look the other way, but this don't fix the problem .....
